title: [ArkaDB]
description: [ArkaDB is a simple CRUD like database implemented in PHP without any third-party dependencies that store data in JSON files.]
remote_theme: pages-themes/merlot@v0.2.0

plugins:

- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads : [true]
