title: [ArkaDB - A simple CRUD DB]
description: [ArkaDB is a simple CRUD like database implemented in PHP without any third-party dependencies that store data in JSON files.]
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 